### ISSUE TITLE
error when creating a services or service works

### ISSUE THREAD

**Issue by jacksolutions** [oerp-odoo/service-management#3]
ValidateError

Error while validating constraint

'bool' object has no attribute 'upper' 

how to solve that? using odoo v8

**Comment by oerp-odoo** [comment]
Hi,
can you give more details? Which module are you using and how you reproduced this validation error?

**Comment by jacksolutions** [comment]
http://awesomescreenshot.com/01553kxc2e

i am using  all this module https://github.com/oerp-odoo/service-management

**Comment by jacksolutions** [comment]
http://awesomescreenshot.com/0c453kxpfd

screenshot of error

**Comment by Robx64** [comment]
I just found that this error appears when you trying to save "OPEN"
project I mean if there is no finish date set. 

Once you set the end date and close project then you can save it. 

Something like that :) 

Pozdrawiam 

ROBERT

**Comment by jacksolutions** [comment]
i dont understand you, can you please attach a screenshot here? i dont have project management app installed in my version.. 

Once you set the end date and close project then you can save it.
=> what is a meaning of it we have to close the project to assign a service works? service works should be assigned to open project only?

**Comment by jacksolutions** [comment]
something is definitely wrong here? or i am not getting your usecase? do you have any usecase for this modules? that will help!

**Comment by oerp-odoo** [comment]
@jacksolutions  can you provide error traceback from log, when you get that error? I can't reproduce it what you get.

**Comment by jacksolutions** [comment]
2015-07-27 07:35:09,923 2075 ERROR domestic openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/custom/addons/calendar_service/models/calendar_service.py", line 260, in create
    rec = super(calendar_service, self).create(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4040, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4225, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/odoo-server/openerp/osv/fields.py", line 748, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4040, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4231, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1288, in _validate_fields
    raise ValidationError("Error while validating constraint\n\n%s" % tools.ustr(e))
ValidationError: ('ValidateError', u"Error while validating constraint\n\n'bool' object has no attribute 'upper'")

**Comment by oerp-odoo** [comment]
@jacksolutions 
This error might pop up when there is no recurrent calendar created (which is required).

Try this workaround. Go to sales/configuration/recurrrent services config. If there are no recurrent calendars, create one. Make sure to add at least one rule (rule items can be empty, if there is nothing planned, but at least one rule must be present). Then make sure to check field `Init`. It is used to generate initial records (you only need to check it once). Then it will generate recurrent services (if there are any non empty rules) and set next generate date to know to which point services were generated to.

Now you can try creating manual services. Manual services usually must have `One Time` type. Recurrent services automatically get `Recurrent` type.

P.S. will need to fix this bug by providing more meaningful warning.

**Comment by jacksolutions** [comment]
Okay i will try those steps and get back to you..

If you have any documentation for how to use it and any use cases that will
surely help...

Thanks

**Comment by jacksolutions** [comment]
i followed the steps that you said but no luck i clicked on "generate recurrent" and i got following error
again in popup

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 393, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/custom/addons/calendar_service/models/calendar_service.py", line 663, in generate_recurrent
    self.set_next_gen_time()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/custom/addons/calendar_service/models/calendar_service.py", line 589, in set_next_gen_time
    next_gen_time = cal_serv_cal.set_utc(next_gen_time) #set time back to UTC
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/calendar_service/models/calendar_service.py", line 490, in set_utc
    local_tz = pytz.timezone(self.env.user.tz)
  File "/usr/lib/python2.7/dist-packages/pytz/__init__.py", line 157, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

**Comment by oerp-odoo** [comment]
This might be because you have not set timezone for your Odoo user. Can you try setting timezone?

**Comment by jacksolutions** [comment]
oh yes sorry, i have sat the timezone now that error gone but i am not able to generate recurrent service, it says this

**Comment by jacksolutions** [comment]
http://awesomescreenshot.com/04b53pjnea

**Comment by jacksolutions** [comment]
infact i dont have any services or services works created... so something is still wrong? i suggest that if you have any use case please send it to me

**Comment by oerp-odoo** [comment]
@jacksolutions 

Please update calendar_service module (and upgrade). Fixed this problem with this commit:

https://github.com/oerp-odoo/service-management/commit/2a6e0228c5f2a67a1457d69dea89e7d0e710eb96

Try it and see if it works for you.

**Comment by jacksolutions** [comment]
@oerp-odoo @Robx64 i have two questions now

1) is it production friendly?
2) do you have any documentation of how to use this software? and the industries where i can offer them?
3) if yes to both of above questions then i can start mobile app for it. :)

**Comment by oerp-odoo** [comment]
1) Well we have a client that uses these modules in production for about 
a year. He is using it for domestic cleaning services (aka house cleaning).
2) Unfortunately we have documentation only in Lithuanian language. We 
would need to write one for English. As for industries, actually could 
be used for any industry that needs some recurrent planning and does 
some repeating services, like cleaning, maintenance, repairing, testing 
(of some kind) etc.
3) Can I ask what kind of app that would be?

On 2015.07.29 10:03, jacksolutions wrote:

> @oerp-odoo https://github.com/oerp-odoo @Robx64 
> https://github.com/Robx64 i have two questions now
> 
> 1) is it production friendly?
> 2) do you have any documentation of how to use this software? and the 
> industries where i can offer them?
> 3) if yes to both of above questions then i can start mobile app for 
> it. :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/oerp-odoo/service-management/issues/3#issuecomment-125864666.

## 

Pagarbiai / Regards

Andrius Laukavičius

Boolit programuotojas / developer

(+370) 52 032 766

dev@boolit.eu mailto:info@oerp.lt

Odoo Partner https://www.odoo.com/partners/NOD-3621

www.oerp.lt http://www.oerp.lt

www.odoolietuva.lt http://www.odoolietuva.lt

**Comment by jacksolutions** [comment]
2) Unfortunately we have documentation only in Lithuanian language. We would need to write one for English. As for industries, actually could be used for any industry that needs some recurrent planning and does some repeating services, like cleaning, maintenance, repairing, testing (of some kind) etc.
=> does google translator works for it?

3) mobile application for the cleaner or staff who can generate the invoices and other thing real time from where they are working sort of!

**Comment by jacksolutions** [comment]
send me documentation i can translate it from google translate if possible!

**Comment by oerp-odoo** [comment]
It should translate, but don't know how well google will translate it and if its enough for you.
Anyway, here is the translation:
http://www.oerp.lt/dokumentacija/dok-01/tvarkarascio-sudarymo-ir-valdymo-sistema

**Comment by jacksolutions** [comment]
okay thank you that really helps!

**Comment by oerp-odoo** [comment]
@jacksolutions  you welcome

**Comment by jacksolutions** [comment]
sorry to reopen it but i have just two questions now.. everything is fine :)

1) http://awesomescreenshot.com/0f753veica
2) when i create a rule in recurrent configuration it says at a time only one recurrent calendars can be active? so what if i want to generate recurrent services for more than one client? cause at a time of generating recurrent calendar i have only 5 clients and i have generated for them but later after 2,3 months if i have more client how can i generate for them?

**Comment by oerp-odoo** [comment]
1) these are for information purposes only. Its used to fill information about place it is going to be cleaned. This repository has many modules, but not all modules are needed for every industry. Some are used specifically for domestic cleaning.
2) Use change rule wizard (next to generate recurrent button). There you can create new rules for new clients and update calendar that is already generated. You can add new services, delete the ones are not needed (if something changes) or update/change times for some rules and update related services times (or only future services times. That depends on case)

P.S. I would suggest you to first try out base modules (calendar_service), then when you are comfortable of what it does, install other modules that extends functionality even further (like integration with timesheets, sale orders, etc).

**Comment by jacksolutions** [comment]
for the point 2) what if customer falls under the same rules then?
http://awesomescreenshot.com/09753vlza2

**Comment by oerp-odoo** [comment]
@jacksolutions 
every customer have their own rule (with its items). Don't understand what you mean by same rules. And for screenshot, I guess you are looking in recurrent events a bit differently. Its purpose is to plan future events. Past events are not important. You can't plan past events, because they already happened. You can plan every event that still has not happened. 

And that next generate time field is used to check, when next recurrent generation should occur. So you actually can put services in time interval like this: `"now"` ->> put any services here `"next generate time"` ->>
Note. Keep in mind that services can't clash with each other, so for example same employee can't be at two services at same time

**Comment by jacksolutions** [comment]
okay got you, you can close it for now..

thank you very much sir..

On Wed, Jul 29, 2015 at 6:01 PM, Andrius Laukavičius <
notifications@github.com> wrote:

> @jacksolutions https://github.com/jacksolutions
> every customer have their own rule (with its items). Don't understand what
> you mean by same rules. And for screenshot, I guess you are looking in
> recurrent events a bit differently. Its purpose is to plan future events.
> Past events are not important. You can't plan past events, because they
> already happened. You can plan every event that still has not happened.
> 
> And that next generate time field is used to check, when next recurrent
> generation should occur. So you actually can put services in time interval
> like this: now ->> put any services here next generate time ->>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oerp-odoo/service-management/issues/3#issuecomment-125936360
> .

## 

Cheers,

Jaykishan Vansadawala
(Jack Solutions)
Mob:- +91-9879455635

**Comment by jacksolutions** [comment]
how can i assigned materials or products that is being used while cleaning? i can use this as a service management but it dont have a module for materials being used while doing the services? can you guide me how can i achieve that?

**Comment by oerp-odoo** [comment]
@jacksolutions please don't pollute same issue with different questions. If you have different issue, create new issue.

There is no such functionality implemented to get into account materials used.

**Comment by jacksolutions** [comment]
i apologize for asking the questions on same issue.. i will create a new
issue if i have any query.

Thanks

On Mon, Aug 17, 2015 at 3:23 PM, Andrius Laukavičius <
notifications@github.com> wrote:

> @jacksolutions https://github.com/jacksolutions please don't pollute
> same issue with different questions. If you have different issue, create
> new issue.
> 
> There is no such functionality implemented to get into account materials
> used.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oerp-odoo/service-management/issues/3#issuecomment-131757644
> .

## 

Cheers,

Jaykishan Vansadawala
(Jack Solutions)
Mob:- +91-9879455635
